### ISSUE TITLE
Discussion on how to detect migrations

### ISSUE THREAD

**Issue by srijan** [greyorange/mnesia_migrate#4]
There are a few different options:
1. Write migrations in `.erl` files at a specified location, and find those files from code.
2. Ensure that migration beam files are at a specified location, and find them that way.
3. Ensure that all migration files follow a specific pattern, then find them using `code:get_path/0` and `filelib:wildcard/1`

The problem with option 2 is that it's difficult to specify a location which can be found both in local dev environments and releases.

**Comment by srijan** [comment]
We can also look at how boss_db does this. It's an approach similar to point 1.

See:
https://github.com/ChicagoBoss/ChicagoBoss/blob/master/src/boss/boss_migrate.erl
and https://github.com/ErlyORM/boss_db/blob/master/src/boss_db.erl#L112

**Comment by keeper575-zz** [comment]
Fixed in a0d44b3bf7d914d and option 3 is partially used
